name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "UserResetPasswordLink=${{ secrets.UserResetPasswordLink }}" >> .env
          echo "DoctorResetPasswordLink=${{ secrets.DoctorResetPasswordLink }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "TokenHelper=${{ secrets.TokenHelper }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "SMTP_SENDER=${{ secrets.SMTP_SENDER }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
          echo "RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}" >> .env
          echo "PAYPAL_CLIENTID=${{ secrets.PAYPAL_CLIENTID }}" >> .env
          echo "PAYPAL_CLIENTSECRET=${{ secrets.PAYPAL_CLIENTSECRET }}" >> .env
          echo "CHAT_CONSULATION_LINK=${{ secrets.CHAT_CONSULATION_LINK }}" >> .env
          echo "VIDEO_CONSULTATION_LINK=${{ secrets.VIDEO_CONSULTATION_LINK }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "Admin_Id=${{ secrets.Admin_Id }}" >> .env

      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: docker build -t krishnadas008/maitri-bookingwebsite-backend .

      - name: Publish image to docker hub
        run: docker push krishnadas008/maitri-bookingwebsite-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull krishnadas008/maitri-bookingwebsite-backend:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container --env-file .env krishnadas008/maitri-bookingwebsite-backend:latest
